# Generated by Django 4.1.1 on 2023-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=400, null=True, verbose_name='سایز')),
                ('metraj', models.CharField(blank=True, max_length=400, null=True, verbose_name='متراژ')),
                ('colore', models.CharField(blank=True, max_length=400, null=True, verbose_name='رنگ')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='آدرس ایمیل')),
                ('phone', models.CharField(blank=True, max_length=400, null=True, verbose_name='شماره تماس')),
                ('home_phone', models.CharField(blank=True, max_length=400, null=True, verbose_name='شماره تماس')),
                ('name_products', models.CharField(blank=True, max_length=400, null=True, verbose_name='محصول')),
                ('addr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس')),
                ('national_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد ملی')),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس پستی')),
                ('transport_1', models.BooleanField(blank=True, default=False, null=True, verbose_name='پیک فقط برای شهر تهران')),
            ],
            options={
                'verbose_name_plural': '8. سفارشات',
            },
        ),
    ]
