# Generated by Django 4.1.1 on 2023-04-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام برند')),
            ],
            options={
                'verbose_name_plural': '3. Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name_plural': '2. Categories',
            },
        ),
        migrations.CreateModel(
            name='Metraj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='متراژ')),
            ],
            options={
                'verbose_name_plural': '4. Metraj',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=400, verbose_name='نام محصول')),
                ('slug', models.CharField(db_index=True, max_length=400, unique=True, verbose_name='نامک')),
                ('short_discration', models.CharField(blank=True, max_length=200, null=True, verbose_name='توظیحات کوتاه')),
                ('detail', models.TextField(verbose_name='جزییات محصول')),
                ('specs', models.TextField(blank=True, null=True, verbose_name='مشخصات فنی')),
                ('colors', models.CharField(max_length=800, verbose_name=' ,رنگ محصول | جدا کننده با ')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس محصول.1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس محصول.2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس محصول.3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس محصول.4')),
                ('status', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='برند محصول')),
                ('category', models.ManyToManyField(blank=True, null=True, to='products.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name_plural': '6. Products',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='سایز')),
            ],
            options={
                'verbose_name_plural': '5. Sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت')),
                ('metraj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.metraj', verbose_name='متراژ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='نام محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name_plural': '7. ProductAttributes',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='عکس محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name_plural': '1. Images',
            },
        ),
    ]
